[[Xorg_libXau]]
arch = "aarch64"
git-tree-sha1 = "ecda85b9e2d1d990598afd51d07b8dfe0c11a349"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "99a82addba39966d07c51a98d86d016e2687e498d521cfab0c91a10facc63616"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.aarch64-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "aarch64"
git-tree-sha1 = "7091cb06c3563a758bfc6f5e3b2dc7e47789a53e"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "f4508cb78692593d8fb695396d264446ff8d944f90498f42ea3a56fc4a0a384b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.aarch64-linux-musl.tar.gz"
[[Xorg_libXau]]
arch = "aarch64"
git-tree-sha1 = "bac42c20ba542b72a948e415fdbec81e1e73e1b4"
os = "freebsd"

    [[Xorg_libXau.download]]
    sha256 = "6eca56740c9d366a1c9392464b948076a933b46aa8431636881593141cd86d45"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.aarch64-unknown-freebsd.tar.gz"
[[Xorg_libXau]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "980124bd07e8f5116443706a47cddd0041e33bde"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "bd97d7b2a8516b2b65b3d6eb77636c0f52b32dc4bd168be4c4a6f139ffdb93c2"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libXau]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3d30e9f0703980cbeae807c9689de6522569aa25"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "c6440f0e3b7a8151c69a79363290f1d4d6710c6a3d227290d3154cde6ca31e57"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libXau]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a22f85160c273762525b3a0eca2f117c986f73fd"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "72b5c1b08e746b247ae017610ec9ac5f19f00306578b71c300d2e88fe9ab7b8c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXau]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5eea36557cdbadef46334abf14e64e8e53ab460c"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "6e30dab4939163c4f42c5d9ab29c1b5bb81c82ea9614f99f9dfe277f7b99fece"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXau]]
arch = "i686"
git-tree-sha1 = "310dd4dc9f60f42a0034c75e4ac2654b38a82617"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "d4b4ba398563896b263057a9a85e8beb4ae40948fcc890c67581b08a3fa1b706"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.i686-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "i686"
git-tree-sha1 = "30d877a10f7cffecdf839e18092c9a3ba03e3a8d"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "b49dbcc47e4a6f834c35135e9483e276c7c5236765ed6e33c9db96df465bd667"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.i686-linux-musl.tar.gz"
[[Xorg_libXau]]
arch = "powerpc64le"
git-tree-sha1 = "0207295f77d65d7cad23e496e56e0d378494de9a"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "29ce271c48007ec38e825257c64cbb72b28b852f50e16d77739249b1cf039424"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "x86_64"
git-tree-sha1 = "7328e6b9e83b8ce9ad81ab14feff0d72eca94bb7"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "882d4980375e33e954130b0e749a9d4f2f4b7a468c7351606dbc2fc2613a52b7"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.x86_64-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "x86_64"
git-tree-sha1 = "2dc147ac4225d7794676c826d5e489843394530a"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "10e4fa0e1a4ba90978c8217a2739a02b672ac1d6a5082cdadb3ffa6e3462ac06"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.x86_64-linux-musl.tar.gz"
[[Xorg_libXau]]
arch = "x86_64"
git-tree-sha1 = "e2886ca610fc9c99947791caa459e90993f0001a"
os = "freebsd"

    [[Xorg_libXau.download]]
    sha256 = "a2b58a9e5830f0d2ecfc918a54c98efb47d345b9bd57a54abdeef760b353907c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.11+1/Xorg_libXau.v1.0.11.x86_64-unknown-freebsd.tar.gz"
