[[Xorg_libXau]]
arch = "armv7l"
git-tree-sha1 = "7cd798b4b4a3b206dc14380ff36933fb36d55375"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "180b8cf067962b6e3bbf521aea3db5e5936877c82b6a0b60209731fd6163205b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libXau]]
arch = "i686"
git-tree-sha1 = "40bb0b4ac0007fca644ed370f9e209a764979de6"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "dbf4abc87d4fbcfa9818b2c4419b702fe4863a4e0f311fd54ae929cfbd18c23a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.i686-linux-musl.tar.gz"
[[Xorg_libXau]]
arch = "aarch64"
git-tree-sha1 = "0ffb565b905f3da1346d68696edaa2200e5077de"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "8d7398b4d326d3dda0b36f03ac617e916624e59463ce61244115e3a81b747e17"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.aarch64-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "armv7l"
git-tree-sha1 = "2d034f4a8c9bc62cf7a7d292212be44c8c8c8306"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "fe0cb83d82ce4cc732af3e35eeba9fb09552276d546267e8f1f0189f5fe509db"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libXau]]
arch = "aarch64"
git-tree-sha1 = "8e84ce776f311320045e61768fc8c39419cb4dcb"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "3337a6dc346dacdf4aa58f8e495ef51bc5d457cbdc28ea06b7cacd318d930e8b"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.aarch64-linux-musl.tar.gz"
[[Xorg_libXau]]
arch = "x86_64"
git-tree-sha1 = "8b6377b66e5cfc60c151efbabfb794d0606e3037"
os = "freebsd"

    [[Xorg_libXau.download]]
    sha256 = "5884162f625c26b8b3f2c94f9824c38260911cbef44a94fa7ab64651258eff50"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.x86_64-unknown-freebsd11.1.tar.gz"
[[Xorg_libXau]]
arch = "i686"
git-tree-sha1 = "13b0071f716319b2d173b23d69ac9688533a1768"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "0700f62e5d7920887178adf5dae084f38b49774068c0405d54076abaf88b2490"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.i686-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "x86_64"
git-tree-sha1 = "dab5f0fb02dc610714aa75d577e47742717fb68d"
libc = "musl"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "bc3dfdb5dcdd53a8ec1d689bd7944c5f13aad584c8cc4a35e268a6af6030769a"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.x86_64-linux-musl.tar.gz"
[[Xorg_libXau]]
arch = "x86_64"
git-tree-sha1 = "56066726300a4b2122b15f64cc32770f5ac494c6"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "002905e562f4ee882cf2140f01c307d3128ef6f35a62cc48b60cce28c5b2b141"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.x86_64-linux-gnu.tar.gz"
[[Xorg_libXau]]
arch = "powerpc64le"
git-tree-sha1 = "c969ca17629a1d2885346062180b577032822272"
libc = "glibc"
os = "linux"

    [[Xorg_libXau.download]]
    sha256 = "8ccc0b0bb2a87df1ee469508f7da739cc69c8a2f4ed71299383f661a5efe2a64"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libXau_jll.jl/releases/download/Xorg_libXau-v1.0.9+2/Xorg_libXau.v1.0.9.powerpc64le-linux-gnu.tar.gz"
